const weatherIconByCode: Record<number, string> = {
  1: 'cloudy',
  2: 'day',
  3: 'cloudy-day-1',
  4: 'cloudy-day-2',
  5: 'cloudy-day-3',
  6: 'cloudy',
  7: 'cloudy',
  8: 'cloudy',
  9: 'cloudy',
  10: 'rainy-4',
  11: 'rainy-5',
  12: 'rainy-2',
  13: 'rainy-3',
  14: 'thunder',
  15: 'thunder',
  16: 'snowy-4',
  17: 'snowy-5',
  18: 'snowy-2',
  19: 'snowy-3',
  20: 'snowy-6',
  21: 'snowy-6',
  22: 'snowy-6',
  23: 'snowy-6',
  24: 'snowy-6',
  25: 'snowy-6',
  26: 'night',
  27: 'cloudy-night-1',
  28: 'cloudy-night-2',
  29: 'cloudy-night-3',
  30: 'cloudy',
  31: 'cloudy',
  32: 'rainy-4',
  33: 'thunder',
  34: 'snowy-4',
  35: 'snowy-6',
  36: 'snowy-6'
}

const weatherLabelByCode: Record<number, string> = {
  1: 'WEATHER',
  2: 'SUNNY',
  3: 'MOSTLY SUNNY',
  4: 'PARTLY SUNNY',
  5: 'MOSTLY CLOUDY',
  6: 'CLOUDY',
  7: 'OVERCAST',
  8: 'LOW CLOUDS',
  9: 'FOGGY',
  10: 'LIGHT RAIN',
  11: 'RAIN',
  12: 'POSSIBLE RAIN',
  13: 'SHOWERS',
  14: 'STORM',
  15: 'LOCAL STORMS',
  16: 'LIGHT SNOW',
  17: 'SNOW',
  18: 'POSSIBLE SNOW',
  19: 'SNOW SHOWERS',
  20: 'RAIN + SNOW',
  21: 'RAIN + SNOW',
  22: 'RAIN + SNOW',
  23: 'FREEZING RAIN',
  24: 'FREEZING RAIN',
  25: 'HAIL',
  26: 'CLEAR',
  27: 'MOSTLY CLEAR',
  28: 'PARTLY CLEAR',
  29: 'MOSTLY CLOUDY',
  30: 'CLOUDY',
  31: 'LOW CLOUDS',
  32: 'SHOWERS',
  33: 'LOCAL STORMS',
  34: 'SNOW SHOWERS',
  35: 'RAIN + SNOW',
  36: 'FREEZING RAIN'
}

export function getWeatherIcon(iconNum: number) {
  return weatherIconByCode[iconNum] ?? 'cloudy'
}

export function getWeatherLabel(iconNum: number, summary: string) {
  return weatherLabelByCode[iconNum] ?? summary.toLocaleUpperCase('en-GB')
}
