name: Frontend Deploy

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/frontend-deploy.yml

jobs:
  frontend-unit-tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4